// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int numberOfRounds = Integer.parseInt(args[0]);
		double over = 0;
		double under = 0;
		while (numberOfRounds>0) {
			if (Math.random() > 0.5){
				over ++;
			}
			else{
				under ++;
			}
			numberOfRounds --;
		}
		double ratio = 0;
		if (over > under) {
			ratio = under/over;
		}
		else{
			ratio = over/under;
		}
		System.out.println("> 0.5: " +(int)over +" times");
		System.out.println("<= 0.5: " +(int)under +" times");
		System.out.println("Ratio: " +ratio);
	}
}
